export const homeContent = {
  hero: {
    eyebrow: 'Yayasan Ibadurrahman · Kota Tangerang',
    title: 'Pendidikan Islami untuk setiap tahap pertumbuhan.',
    description:
      'Mendampingi peserta didik sejak usia dini hingga jenjang menengah atas dengan memadukan ilmu pengetahuan, nilai-nilai Islam, adab, dan pengembangan karakter.',
    primaryCTA: { label: 'Kenali Unit Pendidikan', href: '#unit-pendidikan' },
    secondaryCTA: { label: 'Informasi Pendaftaran', href: '/admissions' },
    image: '/assets/hero/kegiatan-kelas-ibadurrahman.jpeg',
    imagePosition: 'center',
  },
  about: {
    eyebrow: 'Tentang Yayasan',
    title: 'Satu perjalanan pendidikan, dari langkah pertama hingga siap melangkah jauh.',
    description: 'Yayasan Ibadurrahman menaungi pendidikan berjenjang yang mendampingi perkembangan peserta didik secara berkelanjutan. Ilmu, nilai Islam, adab, dan potensi pribadi tumbuh bersama dalam lingkungan yang hangat.',
    image: '/assets/gallery/literasi-santri-ibadurrahman.jpeg',
    button: { label: 'Cerita Kami', href: '/about' },
  },
  values: [
    { number: '01', title: 'Keislaman', description: 'Menjadikan nilai Islam sebagai dasar dalam belajar, bersikap, dan bertumbuh.' },
    { number: '02', title: 'Keilmuan', description: 'Membangun rasa ingin tahu, kebiasaan belajar, dan wawasan yang terus berkembang.' },
    { number: '03', title: 'Adab', description: 'Membiasakan akhlak baik dalam hubungan dengan Allah, keluarga, guru, dan sesama.' },
    { number: '04', title: 'Kemandirian', description: 'Melatih tanggung jawab dan keberanian mengambil peran sesuai tahap perkembangan.' },
    { number: '05', title: 'Kepedulian', description: 'Menumbuhkan empati, kebersamaan, dan kemauan untuk memberi manfaat.' },
    { number: '06', title: 'Potensi', description: 'Memberi ruang bagi setiap anak untuk mengenali dan mengembangkan kekuatannya.' },
  ],
  cta: {
    eyebrow: 'Penerimaan Peserta Didik Baru',
    title: 'Temukan jenjang pendidikan yang tepat untuk putra-putri Anda.',
    description: 'Pilih unit pendidikan yang sesuai dan dapatkan informasi program, lingkungan belajar, serta proses pendaftaran.',
    button: { label: 'Hubungi Admin Pendaftaran', href: '/admissions#kontak-whatsapp' },
  },
  video: {
    eyebrow: 'Kehidupan Sekolah',
    title: 'Belajar, bertumbuh, dan berkarya dalam satu perjalanan.',
    description: 'Lihat gambaran keseharian peserta didik dalam pembelajaran, pembiasaan nilai Islam, dan kegiatan pengembangan diri.',
    thumbnail: '/assets/hero/kegiatan-kelas-ibadurrahman.jpeg',
    videoUrl: '',
  },
  sectionOrder: ['about', 'units', 'values', 'cta', 'programs', 'testimonials', 'video', 'gallery', 'contact'] as const,
  visibility: {
    about: true,
    units: true,
    values: true,
    cta: true,
    programs: true,
    testimonials: true,
    video: true,
    gallery: true,
    contact: true,
  },
} as const;
